name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test on Node.js # GitHub will add ${{ matrix.node-version }} to this title
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        include:
          - node-version: 20.x
            measure_coverage: true

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
        env:
          MEASURE_COVERAGE: ${{ matrix.measure_coverage }}
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.measure_coverage }}
        with:
          name: code-coverage-report
          path: coverage/
          if-no-files-found: error
